server:
  # Render automatically detects port 10000
  port: ${PORT:8083}

spring:
  application:
    name: notification-service

  datasource:
    # Cloud (Railway/Render) Database URL fallback
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecoride_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:sourabh@2003}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    # Security Tip: Inhe Render Environment Variables mein daalna best hai
    username: ${MAIL_USERNAME:sourabhmahajan1111@gmail.com}
    password: ${MAIL_PASSWORD:jzljhtisodmirzsf}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  instance:
    # Cloud discovery ke liye hostname best hai
    prefer-ip-address: false
    hostname: ecoride-notification-service.onrender.com
    non-secure-port: ${server.port}
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      # Aapka live Cloud Eureka URL
      defaultZone: ${EUREKA_SERVER_URL:https://service-registry-qhsy.onrender.com/eureka/}
    register-with-eureka: true
    fetch-registry: true